---


  - name: instalando epel repositorio
    yum:
      name: epel-release
      state: present

  - name: instalando nginx
    yum:
      name:
        - nginx
        - htop
      state: present

  - name: criando diretorio boas praticas
    file :
      path :  /var/www/html
      state :  directory
          
  - name: Ativando e Iniciando Nginx
    service:
      name: nginx
      state: started
      enabled: yes
