---


- name: provisionamento da VM
  hosts: all
  user: vagrant
  become: true

  roles:
    - nginx
    - mariadb
    - php-fpm
    - wordpress


  #TESTE COMMIT

   # - name: modulo alternativo Baixando pasta Wordpress e Forcando instalacao
    #  get_url:
     #   url: https://wordpress.org/latest.tar.gz
      #  dest: /usr/share/nginx/html
       # force_basic_auth: yes

    #- name: Extraindo Pasta Wordpress
     # unarchive:
      #  src: wordpress-4.9.7.tar.gz
       # dest: /usr/share/nginx/html
