---


- name: Criando uma novo Banco com nome 'wordpress'
  mysql_db:
    name: wordpress
    state: present

- name: Baixando Wordpress e Descompactando
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Alterando permissão da pasta wordpress
  file:
    path: "/usr/share/nginx/html/wordpress"
    state: directory
    owner: nginx
    group: nginx
    mode: 0777
