---


- name: Baixando Wordpress e Descompactando
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /var/www/html
    remote_src: yes

- name: Alterando permissão da pasta wordpress
  file:
    path: "/var/www/html/wordpress"
    state: directory
    owner: nginx
    group: nginx
    mode: 0777
